### ISSUE TITLE
use cbase language attr for i18n translation (using symfony translator?)

### ISSUE THREAD

**Issue by jgroenen** [codefornl/clarity#5]

**Comment by milovanderlinden** [comment]
I think you also need i18n on the database level. There are frameworks available that seamlessly integrate i18n into the database. If symfony is your framework of choice, may I suggest looking at propel? http://propelorm.org/documentation/behaviors/i18n.html it will also give you migrations and seeds.

**Comment by jgroenen** [comment]
Curators create curated sets for a specific audience (civil servants), which, I think, includes the language of that specific set. I wouldnt do DB i18n, instead rather offer a clone functionality, to create a similar set in another language.

**Comment by milovanderlinden** [comment]
Closed in favour of #4
